project:
  type: website
  output-dir: docs

website:
  title: "BaBS 3"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: workshop_1.qmd
        text: Workshop 1

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

